#!/usr/bin/env python3
"""Fail if the Hardhat suite's passing count differs from the grand report's (after-action report 12,
audit finding T-2: no guard noticed a deleted test, because the registers are built from recorded runs).

    npx hardhat test | tee /tmp/hh.txt
    python3 docs/testing/check_test_counts.py /tmp/hh.txt

The grand report is regenerated by `python3 sandbox/grand/run.py all`; a change in the number of tests
must come with a regenerated report, so the count every document cites stays true.
"""
import ast
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]


def report_count():
    text = (ROOT / "sandbox/grand/report/GRAND_REPORT.md").read_text()
    m = re.search(r"^\| L1\+L2 \| \S \| (\{.*?\}) \|", text, re.M)
    return ast.literal_eval(m.group(1))["passing"]


def run_count(path):
    m = re.findall(r"^\s*(\d+) passing", pathlib.Path(path).read_text(), re.M)
    if not m:
        raise SystemExit(f"no 'N passing' line in {path}")
    return int(m[-1])


if __name__ == "__main__":
    ran, rep = run_count(sys.argv[1]), report_count()
    if ran != rep:
        print(f"Hardhat ran {ran} passing tests; sandbox/grand/report/GRAND_REPORT.md records {rep}. "
              "Regenerate the grand report (python3 sandbox/grand/run.py all) or restore the tests.")
        sys.exit(1)
    print(f"test count matches the grand report: {ran} passing")
