#!/usr/bin/env python3
"""Generate docs/FEATURE_ASYMMETRY_MATRIX.md from the compiled contract ABIs.

The matrix answers "what can each identity option actually do?" from code, not
from memory of the standards: every function and event comes from
1_blockchain-identity/artifacts (Hardhat output), classified into capability
families by name heuristics that are listed in the output so a reader can audit
them. Hand-written interpretation lives in the companion review, never here.
"""
import json, pathlib, re, collections

ROOT = pathlib.Path(__file__).resolve().parents[2]
ART = ROOT / "1_blockchain-identity" / "artifacts" / "contracts"
OUT = ROOT / "docs" / "FEATURE_ASYMMETRY_MATRIX.md"

# option -> contracts that constitute it (artifact directory names)
OPTIONS = {
    "ERC-1056": ["ERC1056/EthereumDIDRegistry.sol", "ERC1056/CVINVehicleDIDRegistry.sol"],
    "ERC-721": ["ERC721/CVINVehicleNFT.sol", "ERC721/CVIN_NFT_DID_ERC721.sol", "ERC721/CVIN_NFT_DID_ERC721_Monolithic.sol"],
    "ERC-725": ["ERC725/CVIN_DID_ERC725.sol"],
    "ERC-725xy": ["ERC725xy/CVINVehicleERC725XY.sol", "ERC725xy/CVINExecuteTarget.sol"],
    "ERC-735": ["ERC735/CVINVehicleClaimHolder.sol"],
    "ERC-1155": ["ERC1155/CVINVehicleCredential1155.sol"],
    "ERC-4337": ["ERC4337/CVINVehicleAccount.sol", "ERC4337/CVINMinimalEntryPoint.sol"],
    "LSP8": ["LSP8/CVINVehicleLSP8.sol"],
    "CVIN-Combined": ["CVINCombined/CVINCombinedIdentity.sol"],
    "MOBI-VID (I+II)": ["MOBI/ERC1056Registry.sol", "MOBI/MOBIVIDRegistry.sol", "MOBI/MOBIVIDRegistryV2.sol"],
}

# capability families: (label, regex over function/event names, lower-cased)
FAMILIES = [
    ("Identity creation (explicit)", r"(create|register|mint|registervehicle|birth)"),
    ("Ownership / controller change", r"(changeowner|transferownership|transfervehicle|transferfrom|safetransfer|owner)"),
    ("Key / delegate management", r"(delegate|addkey|removekey|getkey|guardian|recover|rotat)"),
    ("Attributes / data store", r"(attribute|setdata|getdata|uri|metadata|servicerecord|entry|value)"),
    ("Claims / credentials", r"(claim|credential|attest|issue|inspection|certif)"),
    ("Revocation / status", r"(revoke|revoc|isrevoked|active|decommission|burn)"),
    ("Delegated / signed (off-chain-authorised) execution", r"(signed|signature|permit|userop|handleop|validateuserop|execute|nonce)"),
    ("Lifecycle events / history", r"(event|history|lifecycle|odometer|record|lookup|changed|lastchanged|previouschange)"),
    ("Authorisation / roles", r"(authori|role|grant|issuer|manufacturer|onlyowner)"),
    ("Token economics (approvals, royalties, payments)", r"(approve|approval|royalty|paytoll|price|fee|balanceof|totalsupply)"),
    ("VIN linkage", r"(vin)"),
    ("DID / resolution helpers", r"(did|resolve|identityowner|identityinfo)"),
]

def load(rel):
    d = ART / rel
    if not d.exists(): return None
    stem = pathlib.Path(rel).stem
    cands = [j for j in d.glob("*.json") if not j.name.endswith(".dbg.json")]
    # prefer the artifact whose contract name matches the .sol file (skips interfaces
    # like IERC735 that live in the same source file)
    cands.sort(key=lambda j: (j.stem != stem, j.name))
    for j in cands:
        data = json.loads(j.read_text())
        if "abi" in data and data.get("contractName") == stem: return data
    for j in cands:
        data = json.loads(j.read_text())
        if "abi" in data and not data.get("contractName", "").startswith("I"): return data
    return None

rows, families_hit, per_fn = [], {}, {}
for opt, rels in OPTIONS.items():
    fns, evs, writes, reads = [], [], 0, 0
    for rel in rels:
        a = load(rel)
        if not a: rows.append((opt, rel, "ARTIFACT MISSING", 0, 0, 0, 0)); continue
        f = [x for x in a["abi"] if x.get("type") == "function"]
        e = [x for x in a["abi"] if x.get("type") == "event"]
        w = sum(1 for x in f if x.get("stateMutability") in ("nonpayable", "payable"))
        rows.append((opt, rel, a.get("contractName", rel), len(f), w, len(f) - w, len(e)))
        fns += [x["name"] for x in f]; evs += [x["name"] for x in e]
    names = [n.lower() for n in fns + evs]
    hit = {}
    for label, rx in FAMILIES:
        m = sorted({n for n in fns + evs if re.search(rx, n.lower())})
        hit[label] = m
    families_hit[opt] = hit
    per_fn[opt] = (sorted(set(fns)), sorted(set(evs)))

lines = ["# Feature-Asymmetry Matrix — what each identity option implements (generated from the compiled ABIs)", "",
         f"*Generated by `4_comparison-framework/feature-matrix/make_feature_matrix.py` from `1_blockchain-identity/artifacts`. "
         "Do not edit by hand; interpretation lives in `docs/REVIEW_02_STATE_AND_PARALLEL_WORK.md` §4 and the thesis.*", "",
         "## 1. Surface size per option", "", "| Option | Contract | Functions | Writes | Reads | Events |", "|---|---|---:|---:|---:|---:|"]
for opt, rel, name, nf, w, r, ne in rows:
    lines.append(f"| {opt} | `{name}` | {nf} | {w} | {r} | {ne} |")
lines += ["", "## 2. Capability families × option (count of matching functions/events; the names are listed in §3)", "",
          "| Capability family | " + " | ".join(OPTIONS) + " |", "|---|" + "---|" * len(OPTIONS)]
for label, _ in FAMILIES:
    cells = []
    for opt in OPTIONS:
        n = len(families_hit[opt][label]); cells.append(f"**{n}**" if n else "—")
    lines.append(f"| {label} | " + " | ".join(cells) + " |")
lines += ["", "Heuristics (name regex, case-insensitive) — auditable:", ""]
for label, rx in FAMILIES: lines.append(f"- {label}: `{rx}`")
lines += ["", "## 3. Matching names per option (the evidence behind §2)", ""]
for opt in OPTIONS:
    lines.append(f"### {opt}")
    for label, _ in FAMILIES:
        m = families_hit[opt][label]
        if m: lines.append(f"- **{label}:** " + ", ".join(f"`{x}`" for x in m))
    fns, evs = per_fn[opt]
    unmatched = [x for x in fns + evs if not any(re.search(rx, x.lower()) for _, rx in FAMILIES)]
    if unmatched: lines.append(f"- *Unclassified:* " + ", ".join(f"`{x}`" for x in sorted(set(unmatched))))
    lines.append("")
lines += ["## 4. What this matrix is and is not", "",
          "- It is the *on-chain* surface. Off-chain capabilities (DID resolution, VC issuance and verification, selective disclosure, in-process PKI) live in `2_w3c-ssi-layer/` and `cv2x-testbed/identity/` and are catalogued in the review, not here.",
          "- A count of 0 means the contract exposes nothing matching the family — which is often the standard's design (e.g. ERC-1056 has no token economics; ERC-721 has no key delegation). Those zeros *are* the asymmetry the thesis discusses.",
          "- Name heuristics can over- or under-match; §3 lists every match so a reader can disagree with a classification and still use the data."]
OUT.write_text("\n".join(lines) + "\n"); print("wrote", OUT, "| contracts:", len(rows))
for opt, rel, name, nf, w, r, ne in rows: print(f"  {opt:<16} {name:<36} fn={nf:<3} w={w:<3} r={r:<3} ev={ne}")
