#!/usr/bin/env python3
"""
generate_scaling_tables.py

Reads ../results/scaling_verify.json (produced by run_verify_richness.py for
Experiment C and run_verify_scaling.py for Experiment D) and emits thesis-ready
artefacts for the §5.9 Scaling & Lifetime Cost sub-section:

  Experiment C (verification latency vs credential richness):
    ../results/scaling_verify_richness.csv    - latency vs N claims (+ SD vs k)
    ../results/scaling_verify_richness.tex    - LaTeX booktabs tabular
    ../results/scaling_verify_richness.png    - line plot (if matplotlib present)

  Experiment D (V2V verification saturation vs neighbor density):
    ../results/scaling_verify_density.csv     - per-interval time vs P
    ../results/scaling_verify_density.tex     - LaTeX booktabs tabular
    ../results/scaling_verify_density.png     - line plot with 100 ms budget

Usage:
  python3 generate_scaling_tables.py [path/to/scaling_verify.json]
"""

import csv
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
RESULTS_DIR = HERE.parent / "results"
DEFAULT_INPUT = RESULTS_DIR / "scaling_verify.json"

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    HAVE_MPL = True
except Exception:
    HAVE_MPL = False


def tex_escape(s: str) -> str:
    repl = {"&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
            "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}",
            "^": r"\textasciicircum{}"}
    return "".join(repl.get(c, c) for c in str(s))


# ---------------------------------------------------------------------------
# Experiment C — credential richness + selective disclosure
# ---------------------------------------------------------------------------

def write_richness_csv(rich, sd, out_path):
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["# Experiment C: VC verification latency vs credential richness"])
        w.writerow(["N_claims", "median_ms", "p95_ms", "mean_ms"])
        for N, med, p95, mean in zip(rich["N"], rich["median_ms"],
                                     rich["p95_ms"], rich["mean_ms"]):
            w.writerow([N, med, p95, mean])
        w.writerow([])
        w.writerow([f"# Selective disclosure (N={sd['N']}): latency vs disclosed k"])
        w.writerow(["k_disclosed", "median_ms", "p95_ms", "mean_ms"])
        for k, med, p95, mean in zip(sd["k"], sd["median_ms"],
                                     sd["p95_ms"], sd["mean_ms"]):
            w.writerow([k, med, p95, mean])
        w.writerow([])
        sc = rich["scaling"]
        w.writerow(["# richness scaling order", sc["order"]])
        w.writerow(["# richness fit", f"median_ms = {sc['intercept_ms']} "
                    f"+ {sc['slope_ms_per_unit']}*N  (R^2={sc['r2']})"])
        w.writerow(["# sig-check target ms", rich["sig_check_target_ms"]])
        w.writerow(["# p95 under target across range",
                    rich["stays_under_target_across_range"]])
    print(f"Wrote {out_path}")


def write_richness_tex(rich, sd, out_path):
    sc = rich["scaling"]
    target = rich["sig_check_target_ms"]
    caption = (
        "Experiment C: real W3C Verifiable Credential verification latency vs "
        "credential richness. Left: full verification of a credential carrying "
        "$N$ claims. Right: selective disclosure of $k$ of $N=" f"{sd['N']}" "$ "
        "salted claim digests. Each cell is the median over "
        f"{rich['runs_per_point']} warm runs (p95 in parentheses), real "
        "secp256k1 EIP-191 recovery, single host (repeatability framing, thesis "
        f"\\S5.4). Verification is {tex_escape(sc['order'])} in $N$ and remains "
        f"far below the {target:.0f}\\,ms signature-check target across the "
        "whole range."
    )
    lines = [
        "% Auto-generated by generate_scaling_tables.py -- do not edit by hand.",
        "% Requires \\usepackage{booktabs}.",
        "\\begin{table}[htbp]",
        "  \\centering",
        f"  \\caption{{{caption}}}",
        "  \\label{tab:scaling-verify-richness}",
        "  \\footnotesize",
        "  \\begin{tabular}{rr@{\\hskip 2em}rr}",
        "    \\toprule",
        "    \\multicolumn{2}{c}{Credential richness} & "
        "\\multicolumn{2}{c}{Selective disclosure ($N=" f"{sd['N']}" "$)} \\\\",
        "    \\cmidrule(r){1-2}\\cmidrule(l){3-4}",
        "    $N$ claims & median (p95) ms & $k$ disclosed & median (p95) ms \\\\",
        "    \\midrule",
    ]
    rows_left = list(zip(rich["N"], rich["median_ms"], rich["p95_ms"]))
    rows_right = list(zip(sd["k"], sd["median_ms"], sd["p95_ms"]))
    nrows = max(len(rows_left), len(rows_right))
    for i in range(nrows):
        if i < len(rows_left):
            N, med, p95 = rows_left[i]
            left = f"{N} & {med:.4f} ({p95:.4f})"
        else:
            left = " & "
        if i < len(rows_right):
            k, med, p95 = rows_right[i]
            right = f"{k} & {med:.4f} ({p95:.4f})"
        else:
            right = " & "
        lines.append(f"    {left} & {right} \\\\")
    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


def plot_richness(rich, sd, out_path):
    if not HAVE_MPL:
        print("matplotlib not available - skipped richness PNG")
        return
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9, 3.6))
    ax1.plot(rich["N"], rich["median_ms"], "o-", color="#1f77b4",
             label="median")
    ax1.plot(rich["N"], rich["p95_ms"], "s--", color="#7fb0d8", label="p95",
             linewidth=1)
    ax1.set_xscale("log", base=2)
    ax1.set_xticks(rich["N"])
    ax1.set_xticklabels(rich["N"])
    ax1.set_xlabel("credential richness $N$ (claims)")
    ax1.set_ylabel("verification latency (ms)")
    ax1.set_title("(a) latency vs richness")
    ax1.set_ylim(bottom=0)
    ax1.grid(True, alpha=0.3)
    ax1.legend(fontsize=8)

    ax2.plot(sd["k"], sd["median_ms"], "o-", color="#d62728", label="median")
    ax2.plot(sd["k"], sd["p95_ms"], "s--", color="#e58a8b", label="p95",
             linewidth=1)
    ax2.set_xscale("log", base=2)
    ax2.set_xticks(sd["k"])
    ax2.set_xticklabels(sd["k"])
    ax2.set_xlabel(f"disclosed claims $k$ (of $N={sd['N']}$)")
    ax2.set_ylabel("verification latency (ms)")
    ax2.set_title("(b) selective disclosure")
    ax2.set_ylim(bottom=0)
    ax2.grid(True, alpha=0.3)
    ax2.legend(fontsize=8)

    fig.suptitle("Experiment C — VC verification latency vs credential richness "
                 f"(\\ll {rich['sig_check_target_ms']:.0f} ms target)"
                 .replace("\\ll", "«"), fontsize=10)
    fig.tight_layout(rect=(0, 0, 1, 0.94))
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Wrote {out_path}")


# ---------------------------------------------------------------------------
# Experiment D — V2V verification saturation vs neighbor density
# ---------------------------------------------------------------------------

def write_density_csv(dens, out_path):
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["# Experiment D: V2V per-interval verification time vs "
                    "neighbor density"])
        w.writerow(["P_neighbors", "per_interval_median_ms", "per_interval_p95_ms",
                    "per_message_median_ms", "pct_of_100ms_budget"])
        for P, med, p95, pm in zip(dens["P"], dens["per_interval_ms"],
                                   dens["per_interval_p95_ms"],
                                   dens["per_message_median_ms"]):
            w.writerow([P, med, p95, pm,
                        f"{100.0 * med / dens['budget_ms']:.2f}"])
        w.writerow([])
        fit = dens["fit"]
        w.writerow(["# budget ms", dens["budget_ms"]])
        w.writerow(["# saturation_P within range", dens["saturation_P"]])
        w.writerow(["# extrapolated saturation P*",
                    dens["extrapolated_saturation_P"]])
        w.writerow(["# fit", f"per_interval_ms = {fit['intercept_ms']} "
                    f"+ {fit['slope_ms_per_neighbor']}*P  (R^2={fit['r2']})"])
    print(f"Wrote {out_path}")


def write_density_tex(dens, out_path):
    fit = dens["fit"]
    budget = dens["budget_ms"]
    if dens["saturation_P"] is not None:
        sat = f"$P^*={dens['saturation_P']}$ neighbors (within the tested range)"
    else:
        sat = (f"beyond the tested range ($P\\le 80$); extrapolated "
               f"$P^*\\approx{dens['extrapolated_saturation_P']:.0f}$ neighbors")
    caption = (
        "Experiment D: per-vehicle per-interval V2V verification time vs neighbor "
        "density $P$ (the dense-intersection case). Each vehicle verifies $P$ "
        "cached neighbours per 10\\,Hz BSM interval; the median over "
        f"{dens['intervals_per_point']} warm 100\\,ms intervals is reported. "
        "Verification time is linear in $P$ "
        f"($\\approx{fit['slope_ms_per_neighbor']:.4f}$\\,ms/neighbour, "
        f"$R^2={fit['r2']:.4f}$). The saturation point is {sat}. "
        f"Crypto verification load only, excluding radio/MAC "
        "(RESEARCH\\_AUDIT \\S4.4)."
    )
    lines = [
        "% Auto-generated by generate_scaling_tables.py -- do not edit by hand.",
        "% Requires \\usepackage{booktabs}.",
        "\\begin{table}[htbp]",
        "  \\centering",
        f"  \\caption{{{caption}}}",
        "  \\label{tab:scaling-verify-density}",
        "  \\footnotesize",
        "  \\begin{tabular}{rrrr}",
        "    \\toprule",
        f"    Neighbours $P$ & per-interval median (ms) & p95 (ms) & "
        f"\\% of {budget:.0f}\\,ms budget \\\\",
        "    \\midrule",
    ]
    for P, med, p95 in zip(dens["P"], dens["per_interval_ms"],
                           dens["per_interval_p95_ms"]):
        pct = 100.0 * med / budget
        lines.append(f"    {P} & {med:.4f} & {p95:.4f} & {pct:.2f}\\% \\\\")
    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


def plot_density(dens, out_path):
    if not HAVE_MPL:
        print("matplotlib not available - skipped density PNG")
        return
    import numpy as np
    P = dens["P"]
    med = dens["per_interval_ms"]
    budget = dens["budget_ms"]
    fit = dens["fit"]
    extrap = dens["extrapolated_saturation_P"]

    fig, ax = plt.subplots(figsize=(6.4, 4.2))
    # Fit / extrapolation line out to the (extrapolated) saturation point.
    x_max = max(P + [extrap if extrap else max(P)])
    xs = np.linspace(0, x_max * 1.02, 200)
    ys = fit["intercept_ms"] + fit["slope_ms_per_neighbor"] * xs
    ax.plot(xs, ys, "-", color="#999999", linewidth=1,
            label=f"fit {fit['slope_ms_per_neighbor']:.3f} ms/neighbour")
    ax.plot(P, med, "o-", color="#1f77b4", label="measured median")
    ax.axhline(budget, color="#d62728", linestyle="--",
               label=f"{budget:.0f} ms budget")
    if extrap:
        ax.axvline(extrap, color="#2ca02c", linestyle=":",
                   label=f"extrapolated $P^*\\approx${extrap:.0f}")
    ax.set_xlabel("neighbour density $P$ (vehicles verified per 100 ms interval)")
    ax.set_ylabel("per-interval verification time (ms)")
    ax.set_title("Experiment D — V2V verification saturation vs neighbour density")
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    print(f"Wrote {out_path}")


def main():
    input_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_INPUT
    if not input_path.exists():
        sys.exit(f"Input not found: {input_path}\n"
                 "Run the measurement drivers first:\n"
                 "  python3 run_verify_richness.py            (Experiment C)\n"
                 "  python3 ../../cv2x-testbed/sumo/run_verify_scaling.py  (D)")
    data = json.loads(input_path.read_text())
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    if "credential_richness" in data and "selective_disclosure" in data:
        rich = data["credential_richness"]
        sd = data["selective_disclosure"]
        write_richness_csv(rich, sd, RESULTS_DIR / "scaling_verify_richness.csv")
        write_richness_tex(rich, sd, RESULTS_DIR / "scaling_verify_richness.tex")
        plot_richness(rich, sd, RESULTS_DIR / "scaling_verify_richness.png")
    else:
        print("No Experiment C data (credential_richness) in input - skipping C")

    if "v2v_density" in data:
        dens = data["v2v_density"]
        write_density_csv(dens, RESULTS_DIR / "scaling_verify_density.csv")
        write_density_tex(dens, RESULTS_DIR / "scaling_verify_density.tex")
        plot_density(dens, RESULTS_DIR / "scaling_verify_density.png")
    else:
        print("No Experiment D data (v2v_density) in input - skipping D")


if __name__ == "__main__":
    main()
